# Generated by Django 5.0.6 on 2024-11-13 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_bono', models.DateField()),
                ('estado_bono', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Municipalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('especificaciones', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AdultoMayor',
            fields=[
                ('rut_adulto_mayor', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('p_nombre', models.CharField(max_length=20)),
                ('s_nombre', models.CharField(blank=True, max_length=20)),
                ('p_apellido', models.CharField(max_length=20)),
                ('s_apellido', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=40)),
                ('certificado_residencia', models.FileField(blank=True, null=True, upload_to='archivos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleresAPP.comuna')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleresAPP.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('rut_instructor', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('p_nombre', models.CharField(max_length=20)),
                ('s_nombre', models.CharField(blank=True, max_length=20)),
                ('p_apellido', models.CharField(max_length=20)),
                ('s_apellido', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=40)),
                ('valor_hora', models.IntegerField()),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleresAPP.comuna')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleresAPP.genero')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('especificacion', models.CharField(max_length=40)),
                ('stock', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('municipalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleresAPP.municipalidad')),
            ],
        ),
        migrations.CreateModel(
            name='FuncionarioMunicipal',
            fields=[
                ('rut_funcionario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('p_nombre', models.CharField(max_length=20)),
                ('s_nombre', models.CharField(blank=True, max_length=20)),
                ('p_apellido', models.CharField(max_length=20)),
                ('s_apellido', models.CharField(max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('municipalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleresAPP.municipalidad')),
            ],
        ),
        migrations.CreateModel(
            name='PropuestaTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=40)),
                ('horario', models.TimeField()),
                ('estadoSolicitud', models.BooleanField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleresAPP.instructor')),
                ('municipalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleresAPP.municipalidad')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleresAPP.region'),
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=100)),
                ('dia', models.CharField(max_length=40)),
                ('horario', models.TimeField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleresAPP.instructor')),
                ('municipalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleresAPP.municipalidad')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleresAPP.sala')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('estado_solicitud', models.BooleanField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleresAPP.instructor')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleresAPP.material')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleresAPP.taller')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto', models.IntegerField()),
                ('bono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleresAPP.bono')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleresAPP.taller')),
            ],
        ),
        migrations.CreateModel(
            name='TallerAdultoMayor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('adulto_mayor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleresAPP.adultomayor')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleresAPP.taller')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=40)),
                ('contrasenia', models.CharField(max_length=40)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleresAPP.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='ValorizacionTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.IntegerField()),
                ('taller_adulto_mayor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleresAPP.talleradultomayor')),
            ],
        ),
        migrations.AddField(
            model_name='bono',
            name='valorizacion_taller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleresAPP.valorizaciontaller'),
        ),
    ]
