# Generated by Django 5.0.6 on 2024-11-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleresAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
