# Generated by Django 5.0.6 on 2024-11-13 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talleresAPP', '0002_rename_usuario_funcionariomunicipal_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adultomayor',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='funcionariomunicipal',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='user',
            new_name='usuario',
        ),
    ]
