# Generated by Django 5.0.6 on 2024-11-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleresAPP', '0002_alter_region_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='dia',
            field=models.CharField(default='null', max_length=40),
            preserve_default=False,
        ),
    ]
