# Generated by Django 5.0.6 on 2024-11-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleresAPP', '0004_adultomayor_fecha_nacimiento_bono_estado_bono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
