# Generated by Django 5.0.6 on 2024-11-15 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleresAPP', '0005_alter_funcionariomunicipal_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionariomunicipal',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='talleresAPP.usuario'),
        ),
    ]
