# Generated by Django 5.1.3 on 2024-11-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleresAPP', '0007_alter_funcionariomunicipal_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='direccion',
        ),
        migrations.AddField(
            model_name='instructor',
            name='email',
            field=models.EmailField(default='prueba@prueba.com', max_length=254),
            preserve_default=False,
        ),
    ]
